[package]
name = "phoebe"
version = "0.1.0"
authors = ["Arthur Goldman <arthur@goldman-tribe.org>"]
license = "MIT"

[badges]
travis-ci = { repository = "gefjon/phoebe" }

[dependencies]
failure = "0.1"
log = "0.4"
lazy_static = "1.0"
failure_derive = "0.1"
env_logger = "*"
